### ISSUE TITLE
[feature] live js and css reloading using server sent events

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#31]
should wrap this https://github.com/chinedufn/hot-app-replacement by @chinedufn

**Comment by marionebl** [comment]
Appears to compete with #34, #1.
Some history and discussion about HMR approaches in #45 (browerify-hmr vs custom SSE)

In order to implement this there are changes that need to be landed and released:

* [ ] Landed [barracks#!59](https://github.com/yoshuawuyts/barracks/pull/59)
* [ ] Released [barracks#!59](https://github.com/yoshuawuyts/barracks/pull/59)
* [ ] Landed [choo#!203](https://github.com/yoshuawuyts/choo/pull/203)
* [ ] Released [choo#!203](https://github.com/yoshuawuyts/choo/pull/203)

---
Example of choo entry point with HMR enabled:

```js
const html = require('choo/html')
const hmr = require('choo-hmr')
const choo = require('choo')

const app = choo()
app.use(hmr())

app.router([ '/', () => html`<div>hello world</div>`])

const tree = app.start()
document.body.appendChild(tree)
```

**Comment by yoshuawuyts** [comment]
related choo issue https://github.com/yoshuawuyts/choo/issues/295

**Comment by yoshuawuyts** [comment]
implementations:
- https://github.com/bengourley/choo-resume
- https://github.com/bengourley/hot-rld

**Comment by mattdesl** [comment]
You might be interested in following some of the recent LiveReload changes in budo:
https://github.com/mattdesl/budo/issues/194

For example, you can use this in the client to force a style sheet to reload smoothly across all modern browsers:
https://www.npmjs.com/package/reload-css

I chose to go with WebSockets for budo just because they are supported in Edge/IE. I'd be curious to know if SSE has some advantage for live reload purposes, though.

**Comment by yoshuawuyts** [comment]
done!

**Comment by laduke** [comment]
how do you turn it on?

**Comment by mikker** [comment]
@laduke With https://github.com/yoshuawuyts/choo-reload
