### ISSUE TITLE
figure out how to serve bundles from the right locations

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/bankai#32]
https://github.com/yoshuawuyts/choo/pull/73 was tripping up; look into _why_ this happens and at the very least document this behavior

**Comment by timwis** [comment]
Per our convo in IRC, it seems like you can't have client-side/choo routes with more than one resource (ie. `/foo/bar`). If you do, bankai attempts to serve `bundle.js` from `/foo/bar/bundle.js` because the `<script>` tag simply has `src="bundle.js"`. server-router doesn't have a match for this, so it serves the default route, `/`, which serves `index.html`. So it's essentially trying to load `index.html` via the `<script>` tag, which is what throws the `Unexpected token <` error.

We could probably fix this by using `<script src="/bundle.js">` (site-relative), just not sure what that would break.
