### ISSUE TITLE
use browserify options from package.json if available

### ISSUE THREAD

**Issue by fczuardi** [yoshuawuyts/bankai#76]
On a project that already have browserify transforms in the browserify field of package.json, it would be cool to not have to type them all on the `bankai start` cli command as --js.transform... (And maybe to `bankai build` as well)
### Expected behavior:

The command should be able to guess if the user have configured browserify on the package.json file and use those by default.
### Ugly patch for start.js:

``` diff
--- left
+++ right
@@ -55,6 +55,10 @@
   }

   if (opts.js) {
+    try {
+      const pkgOpt = require(cwd + '/package.json').browserify;
+      opts.js = xtend(opts.js, pkgOpt);
+    } catch (e) {};
     const js = bankai.js(browserify, entryFile, opts.js)
     const route = opts.html.entry || '/bundle.js'
     routes.push([route, js])

```

**Comment by yoshuawuyts** [comment]
:100: this would be great

**Comment by marionebl** [comment]
Nice idea! I'm not sure if it is optimal to seize the `browserify` key, though. Can we achieve the same convenience if we read config from the usual places under a `bankai` key. We could do this easily with e.g. [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)

**Comment by fczuardi** [comment]
For reference / parity, budo works with the config in the browserify field. If we go with the proposed bankai key, it would still be useful to have it fallback to the browserify key when a bankai specific one is not present.

**Comment by fczuardi** [comment]
Or some other way to tell bankai to inherit the config of browserify, like ava does for babel config:

```
"ava" {
  "babel": "inherit"
}
```

**Comment by yoshuawuyts** [comment]
I think the `browserify` key makes most sense because:

1. It works the same as with `browserify`, meaning there's nothing new to learn
2. It provides parity with `wzrd`, `budo` and `beefy`, further reducing friction
3. It's easier to upgrade to `bankai` from any other tool

The less special we make `bankai` the better I reckon

**Comment by marionebl** [comment]
Okay, then as a general rule of thumb `browserify => bankai.js` holds true.

I assume we want to allow file based config of all bankai features at some point, so that would mean `bankai` and `browserify` keys can coexist in certain scenarios.

The precedence chain should be `bankai.js > browserify`, `bankai[format] > format-tool` in general, I guess.

**Comment by yoshuawuyts** [comment]
yeah, sounds alright. Though I wonder if we'll ever arrive at a point where we need `bankai` specific config; if we ever reach that point I feel it would be good to take a step back and reflect on what we're doing and if couldn't simplify it hah

**Comment by bcomnes** [comment]
Doesn't this already happen? I set up the basic example to demonstrate this I thought? https://github.com/yoshuawuyts/bankai/tree/master/example/basic

**Comment by yoshuawuyts** [comment]
I think this should work; if not passing `{ basedir: __dirname }` or something to the constructor should probs resolve it - closing for now
